# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a8a41cafe25ee030495b1c346ecb8d7bac74421818b147ee2152bcb7bb26f1f84704b45fd6502499b3ce2312b8b0bfb50e9c618eeca2a1548f7b45bc8802d4

test:
  secret_key_base: 50c88153ece92b0a860c26e4018e2bb1fdef2cd0584b50f8746bc3454b28d0f3420cd1b9955bf02cbff2fa73bfc8b74354a64441f7985cbaa72611a497403029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
